### ISSUE TITLE
C-c n not working to move to next result page

### ISSUE THREAD

**Issue by AtomicNess123** [alraban/org-recoll#10]
I don't know why, but these combo is not working.

**Comment by alraban** [comment]
It works correctly here, perhaps you have something else bound to that key combination that's overriding the key binding?  Does it silently fail or do you see any error messages in the Messages buffer?

As a start, if you focus the org-recoll buffer and press C-h k and then C-c n, what function does the minibuffer tell you is being called?  Also, what happens if you focus the org-recoll buffer and call org-recoll-next-page manually from the M-x menu?

**Comment by AtomicNess123** [comment]
Thanks!
1) It is bound to C-c n, `<menu-bar> <Prelude> <Buffers> <Clean up buffer or region>` ((crux-cleanup-buffer-or-region))
2) It works

**Comment by alraban** [comment]
So it looks like you've bound something else to C-c n globally.  So you'll either need to 1) rebind the crux-related command or 2) create a different binding for org-recoll-next-page.  It's just an issue to work out in your configuration.

I don't use crux so I can't offer any more specific advice there.
